In [20]:
import pandas as pd

In [2]:
df = pd.read_excel('/Users/lucasben/Desktop/Data Viz Data Folder/neighbourhood-profiles-2021-158-model.xlsx')
df

,Neighbourhood Name,West Humber-Clairville,Mount Olive-Silverstone-Jamestown,Thistletown-Beaumond Heights,Rexdale-Kipling,Elms-Old Rexdale,Kingsview Village-The Westway,Willowridge-Martingrove-Richview,Humber Heights-Westmount,Edenbridge-Humber Valley,...,Harbourfront-CityPlace,St Lawrence-East Bayfront-The Islands,Church-Wellesley,Downtown Yonge East,Bay-Cloverhill,Yonge-Bay Corridor,Junction-Wallace Emerson,Dovercourt Village,North Toronto,South Eglinton-Davisville
0,Neighbourhood Number,1,2,3,4,5,6,7,8,9,...,165,166,167,168,169,170,171,172,173,174
1,TSNS 2020 Designation,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Neighbourhood Improvement Area,Neighbourhood Improvement Area,Not an NIA or Emerging Neighbourhood,Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,...,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood,Not an NIA or Emerging Neighbourhood
2,Total - Age groups of the population - 25% sam...,33300,31345,9850,10375,9355,22005,22445,10005,15190,...,28135,31285,22320,17700,16670,12645,23180,12380,15885,22735
3,0 to 14 years,4295,5690,1495,1575,1610,3915,3500,1370,2070,...,2065,2285,895,1055,745,970,3075,1365,1315,2190
4,0 to 4 years,1460,1650,505,505,440,1245,1065,395,520,...,1030,1045,495,480,370,500,1135,445,535,910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2598,Total - Eligibility and instruction in the min...,3875,5540,1325,1370,1520,3460,3140,1275,2100,...,1185,1580,540,720,470,555,2375,1190,1050,1580
2599,Children eligible for instruction in the min...,335,395,120,90,70,240,240,70,225,...,145,200,60,70,80,30,305,130,95,155
2600,Eligible children who have been instructed...,255,245,75,75,60,150,185,45,130,...,70,165,35,55,75,10,190,95,65,105
2601,Eligible children who have not been instru...,75,145,45,25,10,95,55,25,95,...,75,35,25,15,0,20,115,35,30,45
2602,Children not eligible for instruction in the...,3540,5145,1205,1275,1445,3215,2895,1205,1880,...,1040,1380,475,655,385,520,2075,1060,955,1420

In [ ]:
transpose = df.set_index(df.columns[0]).T # transpose data
transpose = transpose.reset_index().rename(columns={'index': 'Neighbourhood'}) # reset the index to make neighbourhood index
transpose

Neighbourhood Name,Neighbourhood,Neighbourhood Number,TSNS 2020 Designation,Total - Age groups of the population - 25% sample data,0 to 14 years,0 to 4 years,5 to 9 years,10 to 14 years,15 to 64 years,15 to 19 years,...,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.,Total - Eligibility for instruction in the minority official language for the population in private households born in 2003 or later - 25% sample data,Children eligible for instruction in the minority official language,Children not eligible for instruction in the minority official language,"Total - Eligibility and instruction in the minority official language, for the population in private households born between 2003 and 2015 (inclusive) - 25% sample data",Children eligible for instruction in the minority official language,Eligible children who have been instructed in the minority official language at the primary or secondary level in Canada,Eligible children who have not been instructed in the minority official language at the primary or secondary level in Canada,Children not eligible for instruction in the minority official language
0,West Humber-Clairville,1,Not an NIA or Emerging Neighbourhood,33300,4295,1460,1345,1485,23640,1860,...,1665,2935,5430,410,5020,3875,335,255,75,3540
1,Mount Olive-Silverstone-Jamestown,2,Neighbourhood Improvement Area,31345,5690,1650,1860,2175,21490,2280,...,1145,2965,7285,510,6780,5540,395,245,145,5145
2,Thistletown-Beaumond Heights,3,Neighbourhood Improvement Area,9850,1495,505,540,455,6615,570,...,395,635,1860,180,1685,1325,120,75,45,1205
3,Rexdale-Kipling,4,Not an NIA or Emerging Neighbourhood,10375,1575,505,615,455,6950,515,...,425,775,1910,135,1770,1370,90,75,25,1275
4,Elms-Old Rexdale,5,Neighbourhood Improvement Area,9355,1610,440,480,685,6355,635,...,355,675,2015,95,1920,1520,70,60,10,1445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Yonge-Bay Corridor,170,Not an NIA or Emerging Neighbourhood,12645,970,500,270,200,10820,340,...,695,330,1075,50,1020,555,30,10,20,520
154,Junction-Wallace Emerson,171,Not an NIA or Emerging Neighbourhood,23180,3075,1135,1020,925,17200,750,...,1185,1105,3580,410,3170,2375,305,190,115,2075
155,Dovercourt Village,172,Not an NIA or Emerging Neighbourhood,12380,1365,445,430,490,9040,460,...,775,570,1665,175,1490,1190,130,95,35,1060
156,North Toronto,173,Not an NIA or Emerging Neighbourhood,15885,1315,535,390,390,12780,465,...,970,550,1620,145,1470,1050,95,65,30,955
157,South Eglinton-Davisville,174,Not an NIA or Emerging Neighbourhood,22735,2190,910,670,610,17495,575,...,1390,730,2570,265,2300,1580,155,105,45,1420

In [7]:
transpose.to_csv('/Users/lucasben/Desktop/Data Viz Data Folder/neighbourhood_profiles_clean.csv', index=False)

In [8]:
list(transpose.columns)

['Neighbourhood',
 'Neighbourhood Number',
 'TSNS 2020 Designation',
 'Total - Age groups of the population - 25% sample data',
 '  0 to 14 years',
 '    0 to 4 years',
 '    5 to 9 years',
 '    10 to 14 years',
 '  15 to 64 years',
 '    15 to 19 years',
 '    20 to 24 years',
 '    25 to 29 years',
 '    30 to 34 years',
 '    35 to 39 years',
 '    40 to 44 years',
 '    45 to 49 years',
 '    50 to 54 years',
 '    55 to 59 years',
 '    60 to 64 years',
 '  65 years and over',
 '    65 to 69 years',
 '    70 to 74 years',
 '    75 to 79 years',
 '    80 to 84 years',
 '    85 years and over',
 '      85 to 89 years',
 '      90 to 94 years',
 '      95 to 99 years',
 '      100 years and over',
 'Total - Distribution (%) of the population by broad age groups - 25% sample data',
 '  0 to 14 years',
 '  15 to 64 years',
 '  65 years and over',
 '    85 years and over',
 'Average age of the population',
 'Median age of the population',
 'Total - Persons in private households - 25% sample data',
 '  Total - Persons in census families',
 '    Married spouses or common-law partners',
 '    Parents in one-parent families',
 '    Children',
 '      In a two-parent family',
 '      In a one-parent family',
 '  Total - Persons not in census families in private households - 25% sample data',
 '    Living alone',
 '    Living with other relatives',
 '    Living with non-relatives only',
 'Number of persons in private households',
 'Total - Marital status for the total population aged 15 years and over - 25% sample data',
 '  Married or living common-law',
 '    Married',
 '    Living common-law',
 '      Living common law - Never married',
 '      Living common law - Separated',
 '      Living common law - Divorced',
 '      Living common law - Widowed',
 '  Not married and not living common-law',
 '    Not married and not living common law - Never married',
 '    Not married and not living common law - Separated',
 '    Not married and not living common law - Divorced',
 '    Not married and not living common law - Widowed',
 'Total - Income statistics in 2020 for the population aged 15 years and over in private households - 25% sample data',
 '  Number of total income recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median total income in 2020  among recipients ($)',
 '    Average total income in 2020 among recipients ($)',
 '  Number of after-tax income recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median after-tax income in 2020 among recipients ($)',
 '    Average after-tax income in 2020 among recipients ($)',
 '  Number of market income recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median market income in 2020  among recipients ($)',
 '    Average market income in 2020 among recipients ($)',
 '  Number of employment income recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median employment income in 2020 among recipients ($)',
 '    Average employment income in 2020 among recipients ($)',
 '  Number of government transfers recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median government transfers in 2020 among recipients ($)',
 '    Average government transfers in 2020 among recipients ($)',
 '  Number of employment insurance benefits recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median employment insurance benefits in 2020 among recipients ($)',
 '    Average employment insurance benefits in 2020 among recipients ($)',
 '  Number of COVID-19 emergency and recovery benefits recipients aged 15 years and over in private households in 2020 - 25% sample data',
 '    Median COVID-19 emergency and recovery benefits in 2020 among recipients ($)',
 '    Average COVID-19 emergency and recovery benefits in 2020 among recipients ($)',
 'Composition of total income in 2020 of the population aged 15 years and over in private households (%) - 25% sample data',
 '  Market income (%)',
 '    Employment income (%)',
 '  Government transfers (%)',
 '    Employment insurance benefits (%)',
 '    COVID-19 - Government income support and benefits (%)',
 '      COVID-19 - Emergency and recovery benefits (%)',
 'Total - Total income groups in 2020 for the population aged 15 years and over in private households - 25% sample data',
 '  Without total income',
 '  With total income',
 '    Under $10,000 (including loss)',
 '    $10,000 to $19,999',
 '    $20,000 to $29,999',
 '    $30,000 to $39,999',
 '    $40,000 to $49,999',
 '    $50,000 to $59,999',
 '    $60,000 to $69,999',
 '    $70,000 to $79,999',
 '    $80,000 to $89,999',
 '    $90,000 to $99,999',
 '    $100,000 and over',
 '      $100,000 to $149,999',
 '      $150,000 and over',
 'Total - After-tax income groups in 2020 for the population aged 15 years and over in private households - 25% sample data',
 '  Without after-tax income',
 '  With after-tax income',
 '    Under $10,000 (including loss)',
 '    $10,000 to $19,999',
 '    $20,000 to $29,999',
 '    $30,000 to $39,999',
 '    $40,000 to $49,999',
 '    $50,000 to $59,999',
 '    $60,000 to $69,999',
 '    $70,000 to $79,999',
 '    $80,000 to $89,999',
 '    $90,000 to $99,999',
 '    $100,000 and over',
 '      $100,000 to $124,999',
 '      $125,000 and over',
 'Total - Employment income groups in 2020 for the population aged 15 years and over in private households - 25% sample data',
 '  Without employment income',
 '  With employment income',
 '    Under $5,000 (including loss)',
 '    $5,000 to $9,999',
 '    $10,000 to $19,999',
 '    $20,000 to $29,999',
 '    $30,000 to $39,999',
 '    $40,000 to $49,999',
 '    $50,000 to $59,999',
 '    $60,000 to $69,999',
 '    $70,000 to $79,999',
 '    $80,000 to $89,999',
 '    $90,000 to $99,999',
 '    $100,000 and over',
 '      $100,000 to $124,999',
 '      $125,000 and over',
 'Total - Income statistics in 2019 for the population aged 15 years and over in private households - 25% sample data',
 '  Number of total income recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median total income in 2019 among recipients ($)',
 '    Average total income in 2019 among recipients ($)',
 '  Number of after-tax income recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median after-tax income in 2019 among recipients ($)',
 '    Average after-tax income in 2019  among recipients ($)',
 '  Number of market income recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median market income in 2019 among recipients ($)',
 '    Average market income in 2019 among recipients ($)',
 '  Number of employment income recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median employment income in 2019 among recipients ($)',
 '    Average employment income in 2019 among recipients ($)',
 '  Number of government transfers recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median government transfers in 2019 among recipients ($)',
 '    Average government transfers in 2019 among recipients ($)',
 '  Number of employment insurance benefits recipients aged 15 years and over in private households in 2019 - 25% sample data',
 '    Median employment insurance benefits in 2019 among recipients ($)',
 '    Average employment insurance benefits in 2019 among recipients ($)',
 'Composition of total income in 2019 of the population aged 15 years and over in private households (%) - 25% sample data',
 '  Market income (%)',
 '    Employment income (%)',
 '  Government transfers (%)',
 '    Employment insurance benefits (%)',
 'Total - Income statistics for persons aged 15 years and over not in economic families in private households - 25% sample data',
 '  Median total income in 2020 ($)',
 '  Average total income in 2020 ($)',
 '  Median after-tax income in 2020 ($)',
 '  Average after-tax income in 2020 ($)',
 'Total - LIM low-income status in 2020 for the population in private households - 25% sample data',
 '  0 to 17 years',
 '    0 to 5 years',
 '  18 to 64 years',
 '  65 years and over',
 'In low income based on the Low-income measure, after tax (LIM-AT)',
 '  0 to 17 years',
 '    0 to 5 years',
 '  18 to 64 years',
 '  65 years and over',
 'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)',
 '  0 to 17 years (%)',
 '    0 to 5 years (%)',
 '  18 to 64 years (%)',
 '  65 years and over (%)',
 'Total - LICO low-income status in 2020 for the population in private households to whom the low-income concept is applicable - 25% sample data',
 '  0 to 17 years',
 '    0 to 5 years',
 '  18 to 64 years',
 '  65 years and over',
 'In low income based on the Low-income cut-offs, after tax (LICO-AT)',
 '  0 to 17 years',
 '    0 to 5 years',
 '  18 to 64 years',
 '  65 years and over',
 'Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)',
 '  0 to 17 years (%)',
 '    0 to 5 years (%)',
 '  18 to 64 years (%)',
 '  65 years and over (%)',
 'Total - Adjusted after-tax family income decile group for the population in private households - 25% sample data',
 '  In bottom half of the distribution',
 '    In bottom decile',
 '    In second decile',
 '    In third decile',
 '    In fourth decile',
 '    In fifth decile',
 '  In top half of the distribution',
 '    In sixth decile',
 '    In seventh decile',
 '    In eighth decile',
 '    In ninth decile',
 '    In top decile',
 'Total - Inequality measures for the population in private households - 25% sample data',
 '  Gini index on adjusted household total income',
 '  Gini index on adjusted household market income',
 '  Gini index on adjusted household after-tax income',
 '  P90/P10 ratio on adjusted household after-tax income',
 'Total - Occupied private dwellings by structural type of dwelling - 25% sample data',
 '  Single-detached house',
 '  Semi-detached house',
 '  Row house',
 '  Apartment or flat in a duplex',
 '  Apartment in a building that has fewer than five storeys',
 '  Apartment in a building that has five or more storeys',
 '  Other single-attached house',
 '  Movable dwelling',
 'Total - Private households by household size - 25% sample data',
 '  1 person',
 '  2 persons',
 '  3 persons',
 '  4 persons',
 '  5 or more persons',
 'Average household size',
 'Total - Household type - 25% sample data',
 '  One-census-family households without additional persons',
 '    Couple-family households',
 '      With children',
 '      Without children',
 '    One-parent-family households',
 '  Multigenerational households',
 '  Multiple-census-family households',
 '  One-census-family households with additional persons',
 '  Two-or-more-person non-census-family households',
 '  One-person households',
 'Total - Income statistics for private households - 25% sample data',
 '  Median total income of household in 2020 ($)',
 '  Average total income of household in 2020 ($)',
 '  Median after-tax income of household in 2020 ($)',
 '  Average after-tax income of household in 2020 ($)',
 'Total - Income statistics for one-person private households - 25% sample data',
 '  Median total income of one-person households in 2020 ($)',
 '  Average total income of one-person households in 2020 ($)',
 '  Median after-tax income of one-person households in 2020 ($)',
 '  Average after-tax income of one-person households in 2020 ($)',
 'Total - Income statistics for two-or-more-persons private households - 25% sample data',
 '  Median total income of two-or-more-person households in 2020 ($)',
 '  Average total income of two-or-more-person households in 2020 ($)',
 '  Median after-tax income of two-or-more-person households in 2020 ($)',
 '  Average after-tax income of two-or-more-person households in 2020 ($)',
 'Total - Household total income groups in 2020 for private households - 25% sample data',
 '  Under $5,000',
 '  $5,000 to $9,999',
 '  $10,000 to $14,999',
 '  $15,000 to $19,999',
 '  $20,000 to $24,999',
 '  $25,000 to $29,999',
 '  $30,000 to $34,999',
 '  $35,000 to $39,999',
 '  $40,000 to $44,999',
 '  $45,000 to $49,999',
 '  $50,000 to $59,999',
 '  $60,000 to $69,999',
 '  $70,000 to $79,999',
 '  $80,000 to $89,999',
 '  $90,000 to $99,999',
 '  $100,000 and over',
 '    $100,000 to $124,999',
 '    $125,000 to $149,999',
 '    $150,000 to $199,999',
 '    $200,000 and over',
 'Total - Household after-tax income groups in 2020 for private households - 25% sample data',
 '  Under $5,000',
 '  $5,000 to $9,999',
 '  $10,000 to $14,999',
 '  $15,000 to $19,999',
 '  $20,000 to $24,999',
 '  $25,000 to $29,999',
 '  $30,000 to $34,999',
 '  $35,000 to $39,999',
 '  $40,000 to $44,999',
 '  $45,000 to $49,999',
 '  $50,000 to $59,999',
 '  $60,000 to $69,999',
 '  $70,000 to $79,999',
 '  $80,000 to $89,999',
 '  $90,000 to $99,999',
 '  $100,000 and over',
 '    $100,000 to $124,999',
 '    $125,000 to $149,999',
 '    $150,000 and over',
 'Total - Private households by tenure - 25% sample data',
 '  Owner',
 '  Renter',
 '  Dwelling provided by the local government, First Nation or Indian band',
 'Total - Occupied private dwellings by condominium status - 25% sample data',
 '  Condominium',
 '  Not condominium',
 'Total - Occupied private dwellings by number of bedrooms - 25% sample data',
 '  No bedrooms',
 '  1 bedroom',
 '  2 bedrooms',
 '  3 bedrooms',
 '  4 or more bedrooms',
 'Total - Occupied private dwellings by number of rooms - 25% sample data',
 '  1 to 4 rooms',
 '  5 rooms',
 '  6 rooms',
 '  7 rooms',
 '  8 or more rooms',
 'Average number of rooms per dwelling',
 'Total - Private households by number of persons per room - 25% sample data',
 '  One person or fewer per room',
 '  More than one person per room',
 'Total - Private households by housing suitability - 25% sample data',
 '  Suitable',
 '  Not suitable',
 'Total - Occupied private dwellings by period of construction - 25% sample data',
 '  1960 or before',
 '  1961 to 1980',
 '  1981 to 1990',
 '  1991 to 2000',
 '  2001 to 2005',
 '  2006 to 2010',
 '  2011 to 2015',
 '  2016 to 2021',
 'Total - Occupied private dwellings by dwelling condition - 25% sample data',
 '  Only regular maintenance and minor repairs needed',
 '  Major repairs needed',
 'Total - Private households by number of household maintainers - 25% sample data',
 '  One-maintainer household',
 '  Two-maintainer household',
 '  Three-or-more-maintainer household',
 'Total - Private households by age of primary household maintainers - 25% sample data',
 '  15 to 24 years',
 '  25 to 34 years',
 '  35 to 44 years',
 '  45 to 54 years',
 '  55 to 64 years',
 '  65 to 74 years',
 '  75 to 84 years',
 '  85 years and over',
 'Total - Occupied private dwellings by housing indicators - 25% sample data',
 "  Total - Households 'spending 30% or more of income on shelter costs' or 'not suitable' or 'major repairs needed'",
 '    Spending 30% or more of income on shelter costs only',
 '    Not suitable only',
 '    Major repairs needed only',
 "    'Spending 30% or more of income on shelter costs' and 'not suitable'",
 "    'Spending 30% or more of income on shelter costs' and 'major repairs needed'",
 "    'Not suitable' and 'major repairs needed'",
 "    'Spending 30% or more of income on shelter costs' and 'not suitable' and 'major repairs needed'",
 '  Acceptable housing',
 'Total - Owner and tenant households with household total income greater than zero, in non-farm, non-reserve private dwellings by shelter-cost-to-income ratio - 25% sample data',
 '  Spending less than 30% of income on shelter costs',
 '  Spending 30% or more of income on shelter costs',
 '    30% to less than 100%',
 'Total - Owner and tenant households with household total income greater than zero and shelter-cost-to-income ratio less than 100%, in non-farm, non-reserve private dwellings by core housing need - 25% sample data',
 '  In core need',
 '  Not in core need',
 'Total - Owner households in non-farm, non-reserve private dwellings - 25% sample data',
 '  % of owner households with a mortgage',
 '  % of owner households spending 30% or more of its income on shelter costs',
 '  % in core housing need',
 '  Median monthly shelter costs for owned dwellings ($)',
 '  Average monthly shelter costs for owned dwellings ($)',
 '  Median value of dwellings ($)',
 '  Average value of dwellings ($)',
 'Total - Tenant households in non-farm, non-reserve private dwellings - 25% sample data',
 '  % of tenant households in subsidized housing',
 '  % of tenant households spending 30% or more of its income on shelter costs',
 '  % in core housing need',
 '  Median monthly shelter costs for rented dwellings ($)',
 '  Average monthly shelter costs for rented dwellings ($)',
 'Total - Households living in a dwelling provided by the local government, First Nation or Indian band in non-farm private dwellings - 25% sample data',
 '  % of households living in a dwelling provided by the local government, First Nation or Indian band spending more than 30% on shelter costs',
 '  Median monthly shelter costs for dwellings provided by local government, First Nation or Indian band ($)',
 '  Average monthly shelter costs for dwellings provided by local government, First Nation or Indian band ($)',
 'Total - Census families in private households by family size - 25% sample data',
 '  2 persons',
 '  3 persons',
 '  4 persons',
 '  5 or more persons',
 'Average size of census families',
 'Total number of census families in private households - 25% sample data',
 '  Total couple families',
 '    Married couples',
 '      With children',
 '      Without children',
 '    Common-law couples',
 '      With children',
 '      Without children',
 '  Total one-parent families',
 '    in which the parent is a woman+',
 '    in which the parent is a man+',
 'Average number of children in census families with children',
 'Total - Income statistics for economic families in private households - 25% sample data',
 '  Median total income of economic family in 2020 ($)',
 '  Average total income of economic family in 2020 ($)',
 '  Median after-tax income of economic family in 2020 ($)',
 '  Average after-tax income of economic family in 2020 ($)',
 '  Average family size of economic families',
 'Total - Income statistics for economic families in private households - 25% sample data',
 '  Median total income of couple-only economic family in 2020 ($)',
 '  Average total income of couple-only economic family in 2020 ($)',
 '  Median after-tax income of couple-only economic family in 2020 ($)',
 '  Average after-tax income of economic family in 2020 ($)',
 '  Average family size of couple-only economic families',
 'Total - Income statistics for couple-with-children economic families in private households - 25% sample data',
 '  Median total income of couple-with-children economic family in 2020 ($)',
 '  Average total income of couple-with-children economic family in 2020 ($)',
 '  Median after-tax income of couple-with-children economic family in 2020 ($)',
 '  Average after-tax income of couple-with-children economic family in 2020 ($)',
 '  Average family size of couple-with-children economic families',
 'Total - Income statistics for one-parent economic families in private households - 25% sample data',
 '  Median total income of one-parent economic family in 2020 ($)',
 '  Average total income of one-parent economic family in 2020 ($)',
 '  Median after-tax income of one-parent economic family in 2020 ($)',
 '  Average after-tax income of one-parent economic family in 2020 ($)',
 '  Average family size of one-parent economic families',
 'Total - Knowledge of official languages for the population in private households - 25% sample data',
 '  English only',
 '  French only',

## **Child Care Centre Data**

In [12]:
import geopandas as gpd
df2 = gpd.read_file('/Users/lucasben/Desktop/Data Viz Data Folder/EarlyON Child and Family Centres Locations - geometry - 4326.geojson')
df2

,_id,service_system_manager,agency,loc_id,program_name,languages,french_language_program,indigenous_program,programTypes,serviceName,...,email,contact_fullname,contact_title,phone,contact_email,dropinHours,registeredHours,virtualHours,centre_type,geometry
0,1,City of Toronto,Regent Park Community Health Centre,13650,101 Spruce St EarlyON Child and Family Centre,,None,None,,Drop-in,...,Shani.Halfon@toronto.ca,Maleda Mulu,PROGRAM MANAGER,416-362-0805 X 230,maledam@regentparkchc.org,Wednesday: 9:00 a.m. - 11:30 a.m.,Thursday: 9:00 a.m. - 11:30 a.m.,None,Centre,MULTIPOINT ((-79.36223 43.66419))
1,2,City of Toronto,West Neighbourhood House O/a St. Christopher H...,14380,1033 EarlyON Child and Family Centre,,None,None,,None,...,Shani.Halfon@toronto.ca,Angela Elzinga Cheng,DIRECTOR OF COMMUNITY PROGRAMS,647-438-0038,angelael@westnh.org,None,None,None,Centre,MULTIPOINT ((-79.41639 43.64097))
2,3,City of Toronto,West Scarborough Neighbourhood Community Centre,12554,2555 EarlyON Child and Family Centre,,None,None,,,...,Jene.Gordon@toronto.ca,Jessie Chen,EARLYON COORDINATOR,416-755-9215 X 242,jessiec@wsncc.org,Monday: 9:00 a.m. - noon ; 1:00 p.m. - 3:30 p...,Monday: 10:00 a.m. - 11:00 a.m. ; 1:00 p.m. -...,None,Centre,MULTIPOINT ((-79.25733 43.73435))
3,4,City of Toronto,Macaulay Centres for Children,12562,2700 Dufferin EarlyON Child and Family Centre,,None,None,,,...,Jene.Gordon@toronto.ca,Julia Weglorz,SUPERVISOR,416-789-7441 X 407,jweglorz@macaulaycentres.org,Monday: 10:00 a.m. - noon ; 3:30 p.m. - 6:00 ...,Tuesday: 10:00 a.m. - noon | Thursday: 10:00...,None,Centre,MULTIPOINT ((-79.45399 43.7017))
4,5,City of Toronto,Regent Park Community Health Centre,13648,38 Regent EarlyON Child and Family Centre,,None,None,,,...,Shani.Halfon@toronto.ca,Maleda Mulu,PROGRAM MANAGER,416-362-0805 X 230,maledam@regentparkchc.org,Monday: 9:00 a.m. - 11:30 a.m. ; 1:00 p.m. - ...,Monday: 9:00 a.m. - 11:30 a.m. ; 1:00 p.m. - ...,None,Centre,MULTIPOINT ((-79.36427 43.6586))
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,226,City of Toronto,Central Eglinton Community Centre,7428,Yonge Eglinton EarlyON Child and Family Centre,,None,None,,,...,Shani.Halfon@toronto.ca,Amanda Young,PROGRAM MANAGER,416-392-0511 X 225,amanda@centraleglinton.com,Monday: 1:30 p.m. - 4:30 p.m. | Tuesday: 1:3...,None,None,Centre,MULTIPOINT ((-79.39369 43.70804))
226,227,City of Toronto,Lumenus Community Services,14265,Yonge Sheppard Centre EarlyON,,None,None,,,...,Jessica.Abraham@toronto.ca,Denise Palermo,SUPERVISOR/MANAGER,416-494-1579 X 4301,dpalermo@lumenus.ca,Monday: 1:30 p.m. - 3:30 p.m. | Tuesday: 9:3...,Monday: 9:30 a.m. - 11:30 a.m. | Tuesday: 1:...,None,Centre,MULTIPOINT ((-79.41007 43.76208))
227,228,City of Toronto,Jane/finch Community and Family Centre,14489,York Woods Library,,None,None,,None,...,Jessica.Abraham@toronto.ca,Alicia Khargie,PROGRAM MANAGER,416-663-2733,aliciao@janefinchcentre.org,None,None,None,Centre,MULTIPOINT ((-79.50736 43.75896))
228,229,City of Toronto,Toronto District School Board,12576,Yorkwoods EarlyON Child and Family Centre,,None,None,,,...,Shani.Halfon@toronto.ca,Kim Fritz,None,416-394-2104,kim.fritz@tdsb.on.ca,Monday: 8:45 a.m. - 12:45 p.m. | Tuesday: 8:...,None,None,Centre,MULTIPOINT ((-79.51388 43.75066))
229,230,City of Toronto,Young Women's Christian Association of Greater...,6412,YWCA Toronto Teen Mothers' EarlyON Child and F...,,None,None,,,...,Jene.Gordon@toronto.ca,Pauline Paterson,MANAGER OF TEEN MOM,416-961-8100,ppaterson@ywcatoronto.org,Tuesday: 4:00 p.m. - 7:00 p.m. | Wednesday: ...,Monday: 9:30 a.m. - noon ; 12:30 p.m. - 5:00 ...,None,Centre,MULTIPOINT ((-79.23155 43.72631))

In [17]:
df2["dropinHours"][226]

'Monday: 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.   | Thursday: 1:30 p.m. - 3:30 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.   | Saturday: 9:30 a.m. - 12:30 p.m.  '

In [18]:
df2["dropinHours"].unique()

array(['Wednesday: 9:00 a.m. - 11:30 a.m.  ', None,
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 1:30 p.m. - 2:30 p.m.   | Tuesday: 9:00 a.m. - noon  ; 10:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 10:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Monday: 10:00 a.m. - noon  ; 3:30 p.m. - 6:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 4:00 p.m.   | Friday: 10:00 a.m. - noon   | Saturday: 10:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 1:00 p.m. - 3:30 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:30 p.m.  ',
       'Wednesday: 1:00 p.m. - 3:30 p.m.  ',
       'Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Wednesday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon   | Thursday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon   | Friday: 7:30 a.m. - 9:00 a.m.  ; 9:30 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 4:00 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 10:00 a.m. - noon  ',
       'Monday: 5:00 p.m. - 7:00 p.m.   | Tuesday: 5:00 p.m. - 7:00 p.m.   | Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: noon - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Tuesday: noon - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Wednesday: 9:30 a.m. - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.  ; 9:30 a.m. - 3:00 p.m.  ; 4:00 p.m. - 8:00 p.m.   | Thursday: 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.  ; 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.   | Friday: 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.  ; 9:30 a.m. - 12:30 p.m.  ; 1:30 p.m. - 5:30 p.m.   | Saturday: 12:30 p.m. - 3:30 p.m.  ',
       'Tuesday: 3:30 p.m. - 5:00 p.m.   | Thursday: 9:30 a.m. - 11:00 a.m.  ',
       'Thursday: 4:00 p.m. - 5:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:30 a.m. - 2:30 p.m.  ; 9:30 a.m. - 6:00 p.m.   | Tuesday: 9:30 a.m. - 12:30 p.m.   | Wednesday: 9:30 a.m. - 2:30 p.m.   | Thursday: 9:30 a.m. - 12:30 p.m.   | Friday: 9:30 a.m. - 2:30 p.m.   | Saturday: 9:30 a.m. - 3:00 p.m.  ',
       'Monday: 10:00 a.m. - 1:00 p.m.   | Tuesday: 1:00 p.m. - 3:45 p.m.   | Thursday: 1:00 p.m. - 3:45 p.m.  ',
       'Wednesday: 9:30 a.m. - 1:00 p.m.   | Friday: 9:30 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 2:00 p.m.   | Tuesday: 9:00 a.m. - 2:00 p.m.   | Wednesday: 9:00 a.m. - 2:00 p.m.   | Thursday: 9:00 a.m. - 2:00 p.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.  ; 5:00 p.m. - 7:00 p.m.   | Tuesday: 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 1:30 p.m. - 3:30 p.m.  ; 4:00 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 12:30 p.m. - 4:15 p.m.   | Tuesday: 12:30 p.m. - 4:15 p.m.   | Wednesday: 12:30 p.m. - 4:15 p.m.   | Thursday: 12:30 p.m. - 4:15 p.m.   | Friday: 12:30 p.m. - 4:15 p.m.   | Saturday: 12:30 p.m. - 3:00 p.m.  ',
       'Monday: 8:45 a.m. - 12:30 p.m.   | Tuesday: 8:45 a.m. - 12:30 p.m.   | Wednesday: 8:45 a.m. - 12:30 p.m.   | Thursday: 8:45 a.m. - 12:30 p.m.   | Friday: 8:45 a.m. - 12:30 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 7:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 4:30 p.m. - 7:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - 12:30 p.m.  ',
       'Tuesday: 1:30 p.m. - 3:00 p.m.  ',
       'Monday: 9:15 a.m. - 2:15 p.m.   | Tuesday: 9:15 a.m. - 2:15 p.m.   | Wednesday: 9:15 a.m. - 2:15 p.m.   | Thursday: 9:15 a.m. - 2:15 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.   | Wednesday: 1:30 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 11:30 a.m.  ; 1:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ',
       'Tuesday: 10:00 a.m. - 1:00 p.m.   | Thursday: 10:00 a.m. - 1:00 p.m.   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 8:45 a.m. - 1:45 p.m.   | Tuesday: 8:45 a.m. - 1:45 p.m.   | Wednesday: 8:45 a.m. - 1:45 p.m.   | Thursday: 8:45 a.m. - 1:45 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.  ; 4:00 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon  ; 1:00 p.m. - 4:00 p.m.  ',
       'Monday: 10:00 a.m. - 2:00 p.m.   | Tuesday: 10:00 a.m. - 2:00 p.m.   | Wednesday: 10:00 a.m. - 2:00 p.m.   | Thursday: 10:00 a.m. - 2:00 p.m.   | Friday: 10:00 a.m. - 2:00 p.m.  ',
       'Monday: 8:30 a.m. - 1:30 p.m.   | Tuesday: 8:30 a.m. - 1:30 p.m.   | Wednesday: 8:30 a.m. - 1:30 p.m.   | Thursday: 8:30 a.m. - 1:30 p.m.  ',
       'Monday: 8:45 a.m. - 12:45 p.m.   | Tuesday: 8:45 a.m. - 12:45 p.m.   | Wednesday: 8:45 a.m. - 12:45 p.m.   | Thursday: 8:45 a.m. - 12:45 p.m.   | Friday: 8:45 a.m. - 12:45 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - noon   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 4:00 p.m.   | Thursday: 10:00 a.m. - noon   | Saturday: 9:30 a.m. - 11:00 a.m.  ; 11:00 a.m. - 12:30 p.m.  ',
       'Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.  ; noon - 6:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 10:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 2:30 p.m.   | Friday: 9:00 a.m. - 2:30 p.m.   | Saturday: 10:00 a.m. - 2:00 p.m.  ',
       'Monday: 8:00 a.m. - noon   | Tuesday: 8:00 a.m. - noon   | Wednesday: 8:00 a.m. - noon   | Thursday: 8:00 a.m. - noon   | Friday: 8:00 a.m. - noon  ',
       'Monday: 2:00 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 3:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 10:00 a.m. - noon  ',
       'Tuesday: 9:30 a.m. - 3:00 p.m.   | Wednesday: 10:00 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 3:00 p.m.   | Friday: 9:30 a.m. - noon   | Saturday: 9:30 a.m. - noon  ',
       'Tuesday: 9:00 a.m. - noon   | Wednesday: 10:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 2:30 p.m.   | Wednesday: 9:00 a.m. - noon   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:00 a.m.  ',
       'Tuesday: 12:15 p.m. - 3:15 p.m.   | Wednesday: 8:30 a.m. - 11:30 a.m.  ; 12:15 p.m. - 3:15 p.m.  ; 9:00 a.m. - noon  ; 12:30 p.m. - 3:30 p.m.   | Thursday: 12:15 p.m. - 3:15 p.m.  ; 12:30 p.m. - 3:30 p.m.  ',
       'Monday: 10:30 a.m. - noon   | Wednesday: 10:30 a.m. - 12:30 p.m.  ',
       'Monday: 8:15 a.m. - 1:15 p.m.   | Tuesday: 8:15 a.m. - 1:15 p.m.   | Wednesday: 8:15 a.m. - 1:15 p.m.   | Thursday: 8:15 a.m. - 1:15 p.m.  ',
       'Monday: 8:30 a.m. - 12:30 p.m.   | Tuesday: 8:30 a.m. - 12:30 p.m.   | Wednesday: 8:30 a.m. - 12:30 p.m.   | Thursday: 8:30 a.m. - 12:30 p.m.   | Friday: 8:30 a.m. - 12:30 p.m.  ',
       'Sunday: 1:00 p.m. - 4:00 p.m.   | Monday: 9:30 a.m. - 1:00 p.m.   | Tuesday: 9:30 a.m. - 1:00 p.m.   | Wednesday: 9:30 a.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 1:00 p.m.   | Friday: 9:30 a.m. - 1:00 p.m.  ',
       'Monday: 10:30 a.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - 10:15 a.m.  ; 11:15 a.m. - 1:00 p.m.  ; 3:00 p.m. - 3:30 p.m.   | Wednesday: 10:00 a.m. - 10:30 a.m.  ; 11:00 a.m. - 11:30 a.m.  ; 12:30 p.m. - 2:00 p.m.  ; 3:00 p.m. - 5:00 p.m.   | Thursday: 10:00 a.m. - 1:00 p.m.  ; 3:00 p.m. - 5:00 p.m.   | Friday: 10:00 a.m. - 11:00 a.m.  ; noon - 3:00 p.m.  ; 4:00 p.m. - 5:00 p.m.   | Saturday: 3:00 p.m. - 3:30 p.m.  ; 4:00 p.m. - 5:00 p.m.  ',
       'Wednesday: 10:00 a.m. - 11:30 a.m.   | Friday: 10:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 11:30 a.m.   | Saturday: 10:00 a.m. - noon  ; 12:30 p.m. - 2:00 p.m.  ',
       'Monday: 9:00 a.m. - noon   | Tuesday: 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - 11:00 a.m.   | Tuesday: 10:30 a.m. - 11:30 a.m.   | Wednesday: 9:00 a.m. - 10:00 a.m.  ; 9:00 a.m. - 11:00 a.m.   | Thursday: 10:00 a.m. - 11:00 a.m.  ; 10:30 a.m. - 11:30 a.m.  ; 10:00 a.m. - 11:00 a.m.   | Friday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 11:30 a.m.   | Friday: 1:00 p.m. - 3:00 p.m.  ; 9:00 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Saturday: 9:00 a.m. - 2:00 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Wednesday: 10:30 a.m. - 11:30 a.m.  ',
       'Wednesday: 10:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 3:00 p.m.  ',
       'Tuesday: 10:30 a.m. - 11:30 a.m.  ; 1:00 p.m. - 2:00 p.m.  ',
       'Monday: 9:15 a.m. - 1:15 p.m.   | Tuesday: 9:15 a.m. - 1:15 p.m.   | Wednesday: 9:15 a.m. - 1:15 p.m.   | Thursday: 9:15 a.m. - 1:15 p.m.   | Friday: 9:15 a.m. - 1:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:30 p.m.   | Tuesday: 9:00 a.m. - 1:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 12:30 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - 1:30 p.m.  ',
       'Monday: 9:00 a.m. - 7:00 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.   | Wednesday: 9:00 a.m. - 3:00 p.m.   | Friday: 9:00 a.m. - 3:00 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Monday: 9:15 a.m. - noon  ; noon - 3:00 p.m.   | Tuesday: 9:15 a.m. - noon  ; noon - 3:00 p.m.  ; 1:00 p.m. - 3:00 p.m.  ; 3:00 p.m. - 7:00 p.m.   | Wednesday: 9:15 a.m. - noon  ; noon - 4:30 p.m.   | Thursday: 9:15 a.m. - noon  ; noon - 3:00 p.m.   | Friday: 9:30 a.m. - 3:30 p.m.  ',
       'Monday: 10:00 a.m. - 11:30 a.m.   | Tuesday: 10:00 a.m. - noon  ; 3:30 p.m. - 6:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 2:00 p.m. - 3:30 p.m.  ; 4:30 p.m. - 6:30 p.m.   | Saturday: 9:00 a.m. - noon  ',
       'Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon   | Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 1:00 p.m. - 2:45 p.m.   | Thursday: 1:00 p.m. - 2:45 p.m.  ',
       'Tuesday: 9:00 a.m. - noon  ; 4:00 p.m. - 6:00 p.m.   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon  ; 1:30 p.m. - 3:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Monday: 9:00 a.m. - 3:00 p.m.   | Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon  ; 5:00 p.m. - 7:00 p.m.   | Saturday: 9:00 a.m. - 1:00 p.m.  ',
       'Monday: 9:00 a.m. - 2:30 p.m.  ',
       'Tuesday: 9:00 a.m. - noon   | Wednesday: 9:00 a.m. - noon   | Thursday: 9:00 a.m. - noon  ',
       'Monday: 3:30 p.m. - 5:00 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:30 p.m.   | Tuesday: 9:00 a.m. - 3:00 p.m.  ; 5:00 p.m. - 7:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:00 a.m. - 2:00 p.m.  ; 2:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon   | Saturday: 9:30 a.m. - 11:30 a.m.  ',
       'Sunday: 9:30 a.m. - 11:30 a.m.   | Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 11:00 a.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 6:00 p.m. - 7:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Friday: 9:30 a.m. - 11:00 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 6:00 p.m. - 7:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 3:30 p.m. - 5:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 6:00 p.m. - 7:30 p.m.   | Saturday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 4:30 p.m. - 6:30 p.m.  ; 9:30 a.m. - 11:30 a.m.   | Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 1:30 p.m. - 3:30 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.   | Thursday: 1:30 p.m. - 3:00 p.m.  ',
       'Thursday: 10:30 a.m. - 12:30 p.m.  ',
       'Monday: 2:00 p.m. - 6:00 p.m.   | Tuesday: noon - 4:00 p.m.   | Wednesday: noon - 4:00 p.m.   | Thursday: noon - 4:00 p.m.   | Friday: noon - 3:00 p.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 4:00 p.m. - 5:00 p.m.   | Tuesday: 9:30 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 11:00 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Sunday: 1:30 p.m. - 6:30 p.m.   | Monday: 9:00 a.m. - 12:30 p.m.   | Tuesday: 9:00 a.m. - 12:30 p.m.   | Wednesday: 9:00 a.m. - 12:30 p.m.   | Thursday: 1:30 p.m. - 4:30 p.m.   | Friday: 9:00 a.m. - 12:30 p.m.   | Saturday: 9:30 a.m. - noon  ',
       'Thursday: 9:30 a.m. - 11:30 a.m.   | Friday: 9:00 a.m. - 11:30 a.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:30 p.m. - 4:00 p.m.   | Tuesday: 9:00 a.m. - noon  ; 1:30 p.m. - 3:00 p.m.  ; 3:30 p.m. - 5:30 p.m.   | Wednesday: 9:00 a.m. - noon  ; 1:30 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon  ; 1:30 p.m. - 4:00 p.m.   | Friday: 9:00 a.m. - noon  ; 2:30 p.m. - 4:00 p.m.   | Saturday: 9:00 a.m. - 11:30 a.m.  ',
       'Saturday: 9:45 a.m. - 12:30 p.m.  ',
       'Monday: 10:30 a.m. - 1:00 p.m.   | Thursday: 2:00 p.m. - 4:30 p.m.  ',
       'Monday: 4:30 p.m. - 7:30 p.m.   | Tuesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 10:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 10:30 a.m. - 11:30 a.m.   | Tuesday: 9:30 a.m. - 10:30 a.m.  ; 10:30 a.m. - 11:30 a.m.  ; 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 4:30 p.m. - 5:30 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ; 10:30 a.m. - 11:30 a.m.   | Saturday: 10:00 a.m. - noon  ',
       'Monday: 7:45 a.m. - 11:45 a.m.   | Tuesday: 7:45 a.m. - 11:45 a.m.   | Wednesday: 7:45 a.m. - 11:45 a.m.   | Thursday: 7:45 a.m. - 11:45 a.m.   | Friday: 7:45 a.m. - 11:45 a.m.  ',
       'Monday: 9:00 a.m. - 12:30 p.m.   | Tuesday: 9:00 a.m. - 12:30 p.m.   | Wednesday: 9:00 a.m. - 12:30 p.m.  ; 3:30 p.m. - 4:30 p.m.   | Thursday: 9:00 a.m. - 12:30 p.m.   | Friday: 9:00 a.m. - 12:30 p.m.  ',
       'Monday: 9:00 a.m. - 11:30 a.m.   | Tuesday: 9:00 a.m. - 11:30 a.m.   | Thursday: 9:00 a.m. - 11:30 a.m.   | Friday: 9:30 a.m. - 11:30 a.m.  ',
       'Thursday: 9:30 a.m. - 11:30 a.m.  ',
       'Monday: 10:30 a.m. - 11:30 a.m.  ',
       'Tuesday: 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 5:00 p.m. - 6:30 p.m.   | Wednesday: 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:00 p.m.   | Thursday: 8:30 a.m. - 11:30 a.m.   | Friday: 1:30 p.m. - 3:30 p.m.  ; 8:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Saturday: 1:30 p.m. - 3:30 p.m.  ',
       'Monday: 8:15 a.m. - 12:15 p.m.   | Tuesday: 8:15 a.m. - 12:15 p.m.   | Wednesday: 8:15 a.m. - 12:15 p.m.   | Thursday: 8:15 a.m. - 12:15 p.m.   | Friday: 8:15 a.m. - 12:15 p.m.  ',
       'Monday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Tuesday: 2:00 p.m. - 4:00 p.m.   | Wednesday: 9:00 a.m. - noon  ; 2:00 p.m. - 4:00 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 8:30 a.m. - 4:15 p.m.   | Tuesday: 8:45 a.m. - 6:00 p.m.   | Wednesday: 8:45 a.m. - 6:00 p.m.   | Thursday: 8:45 a.m. - 4:15 p.m.   | Friday: 8:45 a.m. - 4:15 p.m.  ',
       'Monday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Tuesday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Wednesday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Thursday: 9:00 a.m. - 1:00 p.m.  ; 2:30 p.m. - 6:00 p.m.   | Friday: 9:00 a.m. - 1:00 p.m.   | Saturday: 9:00 a.m. - 11:00 a.m.  ',
       'Monday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Wednesday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Thursday: 9:30 a.m. - 11:30 a.m.  ; 1:30 p.m. - 3:30 p.m.   | Friday: 9:30 a.m. - 11:30 a.m.   | Saturday: 9:30 a.m. - noon  ; 12:30 p.m. - 2:00 p.m.  ',
       'Tuesday: 9:30 a.m. - 11:30 a.m.  ; 1:00 p.m. - 3:00 p.m.   | Wednesday: 11:30 a.m. - 3:00 p.m.   | Thursday: 9:30 a.m. - 10:30 a.m.  ; 11:30 a.m. - 1:00 p.m.   | Friday: 4:00 p.m. - 6:00 p.m.  ',
       'Monday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Tuesday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Wednesday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Thursday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.   | Friday: 10:00 a.m. - noon  ',
       'Monday: 9:00 a.m. - noon   | Wednesday: 1:30 p.m. - 3:30 p.m.   | Thursday: 9:00 a.m. - noon   | Friday: 9:00 a.m. - noon  ',
       'Monday: 9:30 a.m. - noon  ; 1:00 p.m. - 3:00 p.m.   | Tuesday: 1:00 p.m. - 3:00 p.m.   | Wednesday: 9:30 a.m. - noon   | Thursday: 9:30 a.m. - noon  ; 1:00 p.m. - 2:30 p.m.  ; 4:00 p.m. - 6:30 p.m.   | Friday: 10:00 a.m. - noon  ; 2:00 p.m. - 3:00 p.m.  ',
       'Monday: 9:00 a.m. - 1:30 p.m.   | Tuesday: 1:00 p.m. - 5:30 p.m.   | Thursday: 9:00 a.m. - 1:30 p.m.   | Friday: 9:00 a.m. - 1:30 p.m.   | Saturday: 9:30 a.m. - 12:30 p.m.  ',

In [21]:
import re
import numpy as np
def categorize_hours(text):
    if pd.isna(text) or not isinstance(text, str) or text.strip() == "":
        return "Other"
    
    t = text.lower()
    
    # Detect days
    days = re.findall(r"(monday|tuesday|wednesday|thursday|friday|saturday|sunday)", t)
    unique_days = set(days)
    
    # Detect if weekend present
    weekend = bool({"saturday", "sunday"} & unique_days)
    
    # Detect time ranges
    evening = bool(re.search(r"(5|6|7|8|9):\d{0,2}\s*p\.?m\.?", t))
    morning = bool(re.search(r"(7|8|9|10|11):\d{0,2}\s*a\.?m\.?", t))
    afternoon = bool(re.search(r"(12|1|2|3|4):\d{0,2}\s*p\.?m\.?", t))
    
    # Apply logic
    if weekend:
        return "Weekend available"
    elif evening:
        return "Evening available"
    elif morning and afternoon:
        return "Full day"
    elif morning:
        return "Morning only"
    elif afternoon:
        return "Afternoon only"
    else:
        return "Other"

# Apply to your dataframe
df2["hourCategory"] = df2["dropinHours"].apply(categorize_hours)

df2["hourCategory"]

0           Morning only
1                  Other
2      Weekend available
3      Weekend available
4               Full day
             ...
225    Weekend available
226    Weekend available
227                Other
228             Full day
229    Evening available
Name: hourCategory, Length: 230, dtype: object

In [23]:
df2["hourCategory"].unique()

array(['Morning only', 'Other', 'Weekend available', 'Full day',
       'Afternoon only', 'Evening available'], dtype=object)